-- Script generated by Lokasenna's GUI Builder


local lib_path = reaper.GetExtState("Lokasenna_GUI", "lib_path_v2")
if not lib_path or lib_path == "" then
  reaper.MB("Couldn't load the Lokasenna_GUI library. Please run 'Set Lokasenna_GUI v2 library path.lua' in the Lokasenna_GUI folder.", "Whoops!", 0)
  return
end
loadfile(lib_path .. "Core.lua")()

GUI.req("Classes/Class - TextEditor.lua")()
GUI.req("Classes/Class - Button.lua")()
-- If any of the requested libraries weren't found, abort the script.
if missing_lib then return 0 end



GUI.name = "TrackCreator - Paste in a list of tracks to create!"
GUI.x, GUI.y, GUI.w, GUI.h = 0, 0, 336, 364
GUI.anchor, GUI.corner = "mouse", "C"

GUI.New("TrackList", "TextEditor", {
  z = 11,
  x = 64,
  y = 16,
  w = 256,
  h = 300,
  caption = "Track list:",
  font_a = 3,
  font_b = "monospace",
  color = "txt",
  col_fill = "elm_fill",
  cap_bg = "wnd_bg",
  bg = "elm_bg",
  shadow = true,
  pad = 4,
  undo_limit = 20
})

function ok()
  local trackListContents = GUI.Val("TrackList")
  local lines = {}

  for line in trackListContents:gmatch("[^\r\n]+") do
    table.insert(lines, line)
  end

  for i = 1, #lines do
    reaper.InsertTrackAtIndex(reaper.GetNumTracks(), true)
    local newTrack = reaper.GetTrack(0, reaper.GetNumTracks()-1)
    reaper.GetSetMediaTrackInfo_String(newTrack, "P_NAME", lines[i], true)
  end
end

GUI.New("OK", "Button", {
  z = 11,
  x = 272,
  y = 320,
  w = 48,
  h = 24,
  caption = "OK",
  font = 3,
  col_txt = "txt",
  col_fill = "elm_frame",
  func = ok
})

GUI.Init()
GUI.Main()
